{
  "html.label.i18n.sidebar.list": "翻译一览",
  "html.label.i18n.sidebar.add": "添加翻译",
  "html.label.i18n.category": "分类",
  "html.label.i18n.key": "词条标识",
  "html.label.i18n.translation": "翻译",
  "html.label.i18n.language": "语言",
  "html.label.i18n.addLanguage": "追加语言",
  "html.label.i18n.status": "翻译状态",
  "js.i18n.check.search": "请输入分类或词条标识！",
  "js.i18n.check.translation.empty": "翻译不能为空！",
  "js.i18n.check.key.empty": "词条标识不能为空！",
  "html.label.common.operation": "操作",
  "js.common.dialog.ok":"确定",
  "js.common.dialog.cancel":"取消",
  "js.common.delete.confirm":"确定删除吗?",
  "js.common.save.success":"保存成功",
  "js.common.save.error":"保存失败",
  "js.common.delete.success":"删除成功",
  "js.common.delete.error":"删除失败",
  "js.common.add.error": "新增失败",
  "js.common.update.error": "更新失败",
  "js.common.search.error": "查询失败",
  "html.button.common.save": "保存",
  "html.button.common.close": "关闭",
  "html.button.common.edit": "编辑",
  "html.button.common.delete": "删除",
  "html.button.common.clear": "清空",
  "html.button.common.select": "选择",
  "html.button.common.search": "搜索"
}